#!/bin/sh

if [ ! -e "fastbuild/linux/fbuild" ]; then
  echo "Not in a Factorio source directory"
  exit
fi

export CC="/usr/bin/gcc-12"
export CXX="/usr/bin/g++-12"
fbuild="fastbuild/linux/fbuild -config fastbuild/fbuild.bff"

mode="debug"
type="run"
if [ "$1" = "test" ]; then
  type="test"
  shift
fi
if [ -n "$1" ]; then
  case $1 in
    compdb)
      $fbuild GCC-Debugx64-factorio-run GCC-Debugx64-factorio-test -compdb
      exit
      ;;
    docs)
      cd scripts/lua_doc
      ./gen-docs.sh
      cd ../..
      exit
      ;;
    *) mode=$1 ;;
  esac
  shift
fi

threads=$FACTORIO_COMPILE_THREADS
if [ -z "$threads" ]; then
  threads=$(grep -c vendor_id /proc/cpuinfo)
  threads=$(($threads - 2))
fi

cmd="$fbuild -j$threads GCC-${mode}x64-factorio-${type}"
echo "$cmd"
$cmd
