#!/bin/sh

if [ ! -e "fastbuild/linux/fbuild" ]; then
  echo "Not in a Factorio source directory"
  exit
fi

export CC="/usr/bin/gcc-12"
export CXX="/usr/bin/g++-12"
fbuild="fastbuild/linux/fbuild -config fastbuild/fbuild.bff"

mode="Debugx64"
type="run"
if [ "$1" = "test" ]; then
  type="test"
  shift
fi
if [ -n "$1" ]; then
  case $1 in
    compdb)
      $fbuild GCC-Debugx64-factorio-run GCC-Debugx64-factorio-test -compdb
      exit
      ;;
    docs)
      cd scripts/lua_doc
      ./gen-docs.py
      cd ../..
      exit
      ;;
    showtargets)
      $fbuild -showtargets
      exit
      ;;
    *)
      parsedmode=$($fbuild -showtargets | grep -i "\b$1" | head -1 | awk -F - '{ print $2 }')
      if [ -n "$parsedmode" ]; then
        mode=$parsedmode
        shift
      fi
      ;;
  esac
fi

threads=$FACTORIO_COMPILE_THREADS
if [ -z "$threads" ]; then
  threads=$(grep -c vendor_id /proc/cpuinfo)
  threads=$(($threads - 2))
fi

cmd="$fbuild -j$threads $@ GCC-${mode}-factorio-${type}"
echo "$cmd"
$cmd

if [ $? -eq 0 ]; then
  notify-send -h string:x-dunst-stack-tag:compilation -c compilation "Compilation finished"
else
  notify-send -u critical -h string:x-dunst-stack-tag:compilation -c compilation "Compilation failed"
fi
