#!/bin/sh

set -e

if [ "$1" = "bg" ]; then
  shift
  frun "$@" < /dev/null > /dev/null 2>&1 & disown
  exit
fi

if [ -e "./server-settings.json" ]; then
  basedir="$PWD"
elif [ -n "$1" ] && [ -e "$FACTORIO/$1" ]; then
  basedir="$FACTORIO/$1"
  shift
else
  basedir="$FACTORIO_DEFAULT"
fi

mode="x64"
bin="factorio"
if [ -e "$basedir/fastbuild/fbuild.bff" ]; then
  mode="Debugx64GCC"
  bin="factorio-run"
  if [ -n "$1" ]; then
    if [ "$1" = "test" ]; then
      bin="factorio-test"
      shift
    fi
    if [ -n "$1" ]; then
      modeinput=$1
      case $1 in
        --*) ;; # Ignore if it's a flag
        docs) # Open Lua documentation
          xdg-open $basedir/scripts/lua_doc/doc-files/index.html < /dev/null > /dev/null 2>&1 & disown
          exit
          ;;
        *)
          parsedmode=$(fd -i -I -t d \\b$1 "$basedir/bin" | head -1 | awk -F / '{ print $(NF-1) }')
          if [ -n "$parsedmode" ]; then
            mode=$parsedmode
            shift
          fi
          ;;
      esac
    fi
  fi
fi

while getopts 'cfl:ms:' c
do
  case $c in
    c) fork=true; mpargs="--mp-connect localhost:34197" ;;
    f) fork=true ;;
    l) fork=true; locale=$OPTARG ;;
    m) fork=true; mpargs="--start-server-load-scenario" ;;
    s) fork=true; mpargs="--start-server $OPTARG" ;;
  esac
done
shift $((OPTIND-1))

# Allow running multiple instances at once
if [ $fork ]; then
  write=$(mktemp -d /tmp/frun.XXX)
  awk -v locale="locale=$locale" -v writedata="write-data=$write" '
    { flag = 1 }
    /write-data/ { flag = 0; print writedata }
    /locale/ { flag = 0; print locale }
    /check-updates/ { flag = 0; print "check-updates=false" }
    flag { print }
  ' $basedir/config/config.ini > $write/config.ini

  ln -s $basedir/atlas-cache.dat $write/atlas-cache.dat
  ln -s $basedir/crop-cache.dat $write/crop-cache.dat

  ln -s $basedir/mods $write/mods
  ln -s $basedir/saves $write/saves
  ln -s $basedir/scenarios $write/scenarios

  ln -s $basedir/server-adminlist.json $write/server-adminlist.json
  ln -s $basedir/server-settings.json $write/server-settings.json

  jq \
    --arg username $(echo "$write" | sed "s~/tmp/frun\.~~") \
    '.["service-username"] = $username | .["service-token"] = ""' \
    $basedir/player-data.json > $write/player-data.json

  echo "Forked - write directory: $write/config.ini"
  forkargs="--config $write/config.ini"
fi

$basedir/bin/$mode$arch/$bin $forkargs $mpargs "$@"

if [ -n "$write" ]; then
  rm -rf $write
fi
