#!/usr/bin/env sh

# modbugbash copies the given save into the Factorio saves folder, syncs mods
# and startup settings with fmm, then launches the game and loads that save
# file.

if [ -z "$FACTORIO_DEFAULT" ]; then
    echo "FACTORIO_DEFAULT environment variable is not defined"
    exit 1
fi

if [ -z "$1" ]; then
    echo "Must provide a save file."
fi

new_location="$FACTORIO_DEFAULT/saves/"$(basename "$1")
mv "$1" "$new_location"
echo "Relocated save file to $new_location"
fmm sync "$new_location"
frun -- --load-game "$new_location"
